---
- name: install nagios for Ubuntu
  apt:
    name:
      - nagios4-core
      - nagios-plugins
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install epel for Centos
  dnf:
    name: epel-release
    use_backend: dnf4
    state: latest
  when: ansible_distribution == "CentOS"

- name: install nagios for Centos
  dnf:
    name:
      - nagios
      - nagios-plugins-all
    use_backend: dnf4
    state: latest
  when: ansible_distribution == "CentOS"
